### ISSUE TITLE
Assertion _points.back().pos > 0 failed (exp.cpp:429)

### ISSUE THREAD

**Issue by popojan** [patnashev/prst#6]
First of all, thank you very much for contributing this great piece of software!

I am using commit tagged v13.0 compiled from source to play a bit with Pocklington primality testing and I have come across a rare failed assertion:

```
$ src/linux64/prst -ini error.ini
```
```
Using Barrett reduction FMA3 FFT length 32.
Pocklington test of 11913195630*199+1, a = 3, complexity = 0.
prst: ../exp.cpp:429: void StrongCheckMultipointExp::init(InputNum*, arithmetic::GWState*, \
    File*, File*, Logging*): Assertion `_points.back().pos > 0' failed.
Aborted (core dumped)
```

for this `error.ini` input:

```
2*3*5*7*59*67*113*127*199+1
[log]
info
```

It may be my misunderstanding of the input format, however this kind of factorized input + 1 works most of the time even for huge numbers.

**Comment by PrestackI** [comment]
@popojan I know you would get better traction on this if you posted your problem to the Software forum on mersenneforum.org.

Here is the link to the latest page: https://www.mersenneforum.org/node/22212/page8#post1053285

FYI, you will need to register for the forum in order to post.
